module.exports = {
  dev: {
    HOST: "GEARHOST_DEV_HOST_URL",
    USER: "GEARHOST_DEV_USER_NAME",
    PASSWORD: "GEARHOST_DEV_USER_PASS",
    DB: "GEARHOST_DEV_DATABASE"
  },
  prod: {
    HOST: "GEARHOST_PROD_HOST_URL",
    USER: "GEARHOST_PROD_USER_NAME",
    PASSWORD: "GEARHOST_PROD_USER_PASS",
    DB: "GEARHOST_PROD_DATABASE"
  }
};
